package Prestamos;

import material.*;
import java.awt.Color;

public class prestamosFrame extends javax.swing.JFrame {
    /**
     * Creates new form materialFrame
     */
    public prestamosFrame() {
        //inicialización de componentes
        initComponents();
        
        
        
        // centra la ventana al medio (850, 450)
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        top_panel = new javax.swing.JPanel();
        exit_button = new javax.swing.JLabel();
        minimize_button = new javax.swing.JLabel();
        left_panel = new javax.swing.JPanel();
        back_button = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tabbed_pane = new javax.swing.JTabbedPane();
        add_tab = new javax.swing.JPanel();
        fill_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        update_tab = new javax.swing.JPanel();
        fill_label1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        search_tab = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Material");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        top_panel.setBackground(new java.awt.Color(92, 0, 0));
        top_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit_button.setBackground(new java.awt.Color(92, 0, 0));
        exit_button.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        exit_button.setForeground(new java.awt.Color(255, 255, 255));
        exit_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit_button.setText("X");
        exit_button.setOpaque(true);
        exit_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit_buttonMouseExited(evt);
            }
        });
        top_panel.add(exit_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 30, 20));

        minimize_button.setBackground(new java.awt.Color(92, 0, 0));
        minimize_button.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        minimize_button.setForeground(new java.awt.Color(255, 255, 255));
        minimize_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize_button.setText("-");
        minimize_button.setOpaque(true);
        minimize_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimize_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimize_buttonMouseExited(evt);
            }
        });
        top_panel.add(minimize_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 30, 20));

        getContentPane().add(top_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 20));

        left_panel.setBackground(new java.awt.Color(92, 0, 0));
        left_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back_button.setText("Regresar");
        left_panel.add(back_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 348, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ITSM_Logo_Oficial.png"))); // NOI18N
        left_panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 350, 110));

        getContentPane().add(left_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 320, 430));

        tabbed_pane.setBackground(new java.awt.Color(171, 0, 51));
        tabbed_pane.setOpaque(true);

        add_tab.setBackground(new java.awt.Color(255, 255, 255));
        add_tab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fill_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fill_label.setText("Rellena los campos para solicitar un prestamo");
        add_tab.add(fill_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nombre del Alumno");
        add_tab.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jTextField1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(171, 0, 51));
        jTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(188, 149, 92)));
        add_tab.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 135, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Matricula");
        add_tab.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        jTextField2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(171, 0, 51));
        jTextField2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(188, 149, 92)));
        add_tab.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 135, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Fecha");
        add_tab.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));

        jTextField3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(171, 0, 51));
        jTextField3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(188, 149, 92)));
        add_tab.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 135, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Cantidad");
        add_tab.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jTextField4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(171, 0, 51));
        jTextField4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(188, 149, 92)));
        add_tab.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 135, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Nombre del material");
        add_tab.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        jTextField5.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(171, 0, 51));
        jTextField5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(188, 149, 92)));
        add_tab.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 135, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Código del Material");
        add_tab.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        jTextField6.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(171, 0, 51));
        jTextField6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(188, 149, 92)));
        add_tab.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 135, -1));

        tabbed_pane.addTab("Prestamos", add_tab);

        update_tab.setBackground(new java.awt.Color(255, 255, 255));
        update_tab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        fill_label1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fill_label1.setText("Registrar ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Nombre");

        jTextField8.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(171, 0, 51));
        jTextField8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(188, 149, 92)));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Matricula");

        jTextField9.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(171, 0, 51));
        jTextField9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(188, 149, 92)));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Número de prestamo");

        jTextField10.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(171, 0, 51));
        jTextField10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(188, 149, 92)));

        jLabel12.setText("Fecha de inicio");

        jLabel13.setText("Fecha de fin");

        javax.swing.GroupLayout update_tabLayout = new javax.swing.GroupLayout(update_tab);
        update_tab.setLayout(update_tabLayout);
        update_tabLayout.setHorizontalGroup(
            update_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(update_tabLayout.createSequentialGroup()
                .addGroup(update_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(update_tabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(fill_label1))
                    .addGroup(update_tabLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(update_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(update_tabLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12))
                            .addGroup(update_tabLayout.createSequentialGroup()
                                .addGroup(update_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 253, Short.MAX_VALUE))
                            .addGroup(update_tabLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addGap(11, 11, 11)))))
                .addGap(93, 93, 93))
        );
        update_tabLayout.setVerticalGroup(
            update_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(update_tabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fill_label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(update_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addGap(0, 0, 0)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(update_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addGap(0, 0, 0)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel11)
                .addGap(0, 0, 0)
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        tabbed_pane.addTab("Registrar", update_tab);

        search_tab.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout search_tabLayout = new javax.swing.GroupLayout(search_tab);
        search_tab.setLayout(search_tabLayout);
        search_tabLayout.setHorizontalGroup(
            search_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );
        search_tabLayout.setVerticalGroup(
            search_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        tabbed_pane.addTab("Historial", search_tab);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        tabbed_pane.addTab("Activos", jPanel1);

        getContentPane().add(tabbed_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 530, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_buttonMouseClicked
        // método que permite cerrar el sistema cuando se hace click en el
        // botón de salir
        System.exit(0);
    }//GEN-LAST:event_exit_buttonMouseClicked

    private void exit_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_buttonMouseEntered
        // método que cambia el fondo del botón cuando el usuario pasa el cursor
        exit_button.setBackground(new Color(62,0,0));
    }//GEN-LAST:event_exit_buttonMouseEntered

    private void exit_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_buttonMouseExited
        // método que cambia el fondo del botón cuando el usuario quita el 
        // cursor
        exit_button.setBackground(new Color(92,0,0));
    }//GEN-LAST:event_exit_buttonMouseExited

    private void minimize_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_buttonMouseClicked
        // método que minimiza la ventana del sistema
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_minimize_buttonMouseClicked

    private void minimize_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_buttonMouseEntered
        // método que cambia el fondo del botón cuando el usuario pasa el cursor
        minimize_button.setBackground(new Color(62,0,0));
    }//GEN-LAST:event_minimize_buttonMouseEntered

    private void minimize_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_buttonMouseExited
        // método que cambia el fondo del botón cuando el usuario quita el 
        // cursor
        minimize_button.setBackground(new Color(92,0,0));
    }//GEN-LAST:event_minimize_buttonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prestamosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prestamosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prestamosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prestamosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prestamosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel add_tab;
    private javax.swing.JButton back_button;
    private javax.swing.JLabel exit_button;
    private javax.swing.JLabel fill_label;
    private javax.swing.JLabel fill_label1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel left_panel;
    private javax.swing.JLabel minimize_button;
    private javax.swing.JPanel search_tab;
    private javax.swing.JTabbedPane tabbed_pane;
    private javax.swing.JPanel top_panel;
    private javax.swing.JPanel update_tab;
    // End of variables declaration//GEN-END:variables
}
